name: crawler->update
on:
  workflow_dispatch:
  schedule:
    - cron: "30 2,9,10 * * *" # UTC
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v3
      - 
        name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - 
        name: crawler
        run: |
          npm install
          npm run build:script
          node dist/scripts/data/crawler.js
      -
        name: setup ali-oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: ${{ secrets.ALI_OSS_ENDPOINT }}
          access-key-id: ${{ secrets.ALI_OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALI_OSS_ACCESS_KEY_SECRET }}
        
      - 
        name: update
        # need to authorize the user of those access keys above, with the write/read operations
        run: ossutil cp -f ./manga-info.json oss://${{ secrets.ALI_OSS_BUCKET }}/manga-info.json --acl public-read